KhronosGroup/Vulkan-ExtensionLayer

CMakeLists.txt

As David pointed out, we don't have any test for now.
Resolves #4.

Drop googletest for now

---

layers/timeline_semaphore.c

It should be failed to get an instance proc address via
vkGetDeviceProcAddr, although it's fine to get device proc
address via vkGetInstanceProcAddr.
Split name_to_funcptr_map into name_to_instance_funcptr_map
and name_to_device_funcptr_map to solve this issue.
Change-Id: I2d352f7b5b825936c1f7b522b6acadd613077b0b

Fix an issue of vkGetDeviceProcAddr

---

layers/timeline_semaphore.c

PhysicalDevice is kind of special, there is no good time to unmap the
physical device. As a consequence, the physical device of previous
instance which has been already destroyed still take the slot in the
map and the new objects can't overwrite the old one with object_map().
Solution:
Create a dedicated map for physical device. It requires another map to
store the physical device and instance if removing physical device from
map while instance is destroyed.
Change-Id: Ifb3f3e6ea029b70f97dad13be1d8db4d91bc4715

Add a global map for physical device

---

layers/timeline_semaphore.c

This partially addresses https://github.com/KhronosGroup/Vulkan-ExtensionLayer/issues/27

Allocation failure fixes

---

README.md

Document implemented extensions (ie. just VK_KHR_timeline_semaphore for now)

---

layers/timeline_semaphore.c

Fixes https://github.com/KhronosGroup/Vulkan-ExtensionLayer/issues/39

Fix incorrect usage of waitDstStageMask in vkQueueSubmit

---

layers/CMakeLists.txt
layers/VkLayer_khronos_timeline_semaphore.def
scripts/check_code_format.py
scripts/clang-format-diff.py
scripts/known_good.json

These changes get the repo ready for a new layer that will implement the VK_KHR_synchronization2 extension.
Changes:
-Update known_good.json
-Add a code format checker from the  KhronosGroup/Vulkan-ValidationLayer repository
-Fix some build metadata files

prepatory changes for VK_KHR_synchronization2 layer

---

layers/synchronization2.cpp

Android Loader for older devices still needs some extra things in order to more universal

Fix hooking into the Android Loader

---

docs/synchronization2_layer.md

Change-Id: Ia4e4a576710776d558274b2427b71c135a771143

docs: Add text about vulkan 1.0

---

layers/json/VkLayer_khronos_synchronization2.json.in

These layers settings will be used to control the layer using Vulkan Configurator.

sync2: add layer settings to manifest file

---

build-android/known_good.json
scripts/known_good.json

Change-Id: I054c77c543ecc7ba155b49ffdebbf9864c04e4b9

build: Update gslang, SPIRV-Headers and Vulkan-Tools known goods

---

build-android/known_good.json
scripts/known_good.json

Change-Id: Ie3f955af4c3e981c4931d8acd0fef000bca862ac

build: update glslang known-good to fix cmake compatibility

---

build-android/known_good.json
scripts/known_good.json

There are no changes to generated code from this header update.

build: Update Vulkan-Headers known good to 1.2.181

---

build-android/known_good.json
scripts/generate_source.py
scripts/known_good.json
utils/generated/vk_safe_struct.cpp
utils/generated/vk_safe_struct.h
utils/generated/vk_typemap_helper.h

Re-enable the VK_HUAWEI_subpass_shading extension.

build: Update Vulkan-Headers to v1.2.189

---

build-android/known_good.json
scripts/known_good.json

No changes to generated source.

build: Update Vulkan-Headers to 1.2.192

---

build-android/known_good.json
scripts/known_good.json

No changes to generated source.

build: Update Vulkan-Headers to 1.2.198

---

build-android/known_good.json
scripts/known_good.json

Now at commit c9706bdda0ac22b9856f1aa8261e5b9e15cd20c5

build: Update gslang known-good again to fix a regression

---

build-android/known_good.json
scripts/known_good.json
utils/generated/vk_safe_struct.cpp
utils/generated/vk_safe_struct.h
utils/generated/vk_typemap_helper.h

Vulkan-Headers and -Tools are 1.3.231
glslang is 5755de46b07e4374c05fb1081f65f7ae1f8cca81
SPIRV-Headers is 85a1ed200d50660786c1a88d9166e871123cce39

build: Update known goods for 1.3.231

---

scripts/utils/utils.py

Addresses https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/145/files

scripts: Address python tarfile exploit

---

CMakeLists.txt
scripts/check_code_format.py
scripts/known_good.json

[cmake: Use VULKAN_HEADERS_REGISTRY_DIRECTORY](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/commit/43697a03ad166e494dae890d5a1cb01940e0dac4)
[cmake: Allow add_subdirectory workflow](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/commit/c26fea5ca6571e79789df0444102f51efdb615ab)
closes https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/156

CMake cleanup

---

.github/workflows/build_android.yml
.github/workflows/build_linux.yml
.github/workflows/build_macos.yml
.github/workflows/build_windows.yml
BUILD.md
README.md
scripts/check_code_format.py
scripts/update_deps.py
tests/extension_layer_tests.cpp

github: Use main instead of master

---

build-android/known_good.json
scripts/helper_file_generator.py
scripts/known_good.json
utils/generated/vk_safe_struct.cpp
utils/generated/vk_safe_struct.h
utils/generated/vk_typemap_helper.h

Also update glslang and SPIRV-Headers for the next release.

build: Update Vulkan-Headers to 1.3.239

---

build-android/known_good.json
layers/synchronization2.cpp
layers/timeline_semaphore.c
scripts/known_good.json
utils/generated/vk_safe_struct.cpp
utils/generated/vk_safe_struct.h
utils/generated/vk_typemap_helper.h
utils/vk_format_utils.cpp
utils/vk_format_utils.h
utils/vk_layer_config.cpp
utils/vk_layer_config.h

Also remove use of VK_LAYER_EXPORT

build: Update Vulkan-Headers to 1.3.241

---

.github/workflows/build_android.yml
.github/workflows/build_linux.yml
.github/workflows/build_macos.yml
.github/workflows/build_windows.yml
build-android/known_good.json
scripts/check_code_format.py
scripts/common_codegen.py
scripts/dispatch_table_helper_generator.py
scripts/generate_source.py
scripts/helper_file_generator.py
scripts/known_good.json
scripts/layer_dispatch_table_generator.py
scripts/lvl_genvk.py
scripts/lvt_file_generator.py
tests/extension_layer_tests.cpp
tests/synchronization2_tests.cpp
tests/vkrenderframework.cpp
tests/vktestbinding.cpp
utils/generated/lvt_function_pointers.cpp
utils/generated/lvt_function_pointers.h
utils/generated/vk_safe_struct.cpp
utils/generated/vk_safe_struct.h
utils/generated/vk_typemap_helper.h

This change also updates the code generation scripts to match the latest from Vulkan-ValidationLayers

build: Update Vulkan-Headers 1.3.245

---

BUILD.md

docs: Remove outdated build instructions

---

build-android/known_good.json
scripts/known_good.json

There are no changes to the generated code from this update.

build: Update to Vulkan-Headers 1.3.247

---

docs/shader_object_layer.md
layers/json/VkLayer_khronos_shader_object.json.in
layers/shader_object.cpp
layers/vk_layer_settings.txt

Add documentation for shader object layer

---

CONTRIBUTING.md
README.md

Now that there are multiple layers in this repo that are actively used, we need to make sure the people who understand each layer are documented and tagged on any Issues.

docs: Update README.md to include layer Point of Contacts

---

build-android/known_good.json
scripts/known_good.json

There are no changes to the generated code from this update.

build: Update to Vulkan-Headers 1.3.248

---

layers/generated/shader_object_constants.h
layers/generated/shader_object_device_data_dynamic_state_adding.inl
layers/generated/shader_object_entry_points_x_macros.inl
layers/generated/shader_object_find_intercepted_dynamic_state_function_by_name.inl
layers/generated/shader_object_full_draw_state_struct_members.inl
layers/generated/shader_object_full_draw_state_utility_functions.inl
layers/shader_object.cpp
scripts/shader_object_data.json
scripts/shader_object_generator.py

This fixes CTS tests using discard rectangles

Add VK_EXT_discard_rectangles to shader object

---

layers/generated/shader_object_constants.h
layers/generated/shader_object_device_data_dynamic_state_adding.inl
layers/generated/shader_object_entry_points_x_macros.inl
layers/generated/shader_object_find_intercepted_dynamic_state_function_by_name.inl
layers/generated/shader_object_full_draw_state_struct_members.inl
layers/generated/shader_object_full_draw_state_utility_functions.inl
layers/shader_object.cpp
scripts/shader_object_data.json
scripts/shader_object_generator.py

This reverts commit 5135e76e8a4fee74e7d73bbf8c90d678ce94f62f.

Revert "shaderObject: Add VK_EXT_discard_rectangles"

---

layers/shader_object.cpp

In x86 VkShaderEXT is defined as uint64_t, when casting to pointers we must index before the cast.

shaderObject: Fix 32 bit pointers

---

BUILD.md
CMakeLists.txt
build-android/known_good.json
scripts/CMakeLists.txt
scripts/common_ci.py
scripts/known_good.json
scripts/update_deps.py
tests/CMakeLists.txt
tests/vktestframework.cpp
tests/vktestframework.h

Required tweaking known_good.json and a couple C++ changes
This PR requires this to be merged in first:
https://github.com/LunarG/VulkanTests/pull/398

Update the CMake code

---

BUILD.md
CMakeLists.txt

These variables don't do anything they were copy pasted from vvl.

cmake: Remove BUILD_LAYERS & BUILD_LAYER_SUPPORT_FILES

---

tests/decompression_tests.cpp

Updated tests to work with portability enumeration extension.

tests: Updated tests for macos

---

build-android/known_good.json
scripts/known_good.json

There are no changes to generated code for this update.

build: Update Vulkan-Headers to 1.3.256

---

CMakeLists.txt
build-android/known_good.json
scripts/known_good.json

build: Update Vulkan-Headers to 1.3.257

---

BUILD.md

The current documentation is extremely out of date.

docs: Update BUILD.md

---

layers/shader_object.cpp

shaderObject: Fix pipelines race condition

---

layers/json/VkLayer_khronos_shader_object.json.in

I'm comfortable removing beta status after #211 #271 and #268 are merged

shaderObject: Remove beta status

---

layers/generated/shader_object_full_draw_state_utility_functions.inl
layers/shader_object.cpp
scripts/shader_object_generator.py

shaderObject: Fix memory allocation alignment

---

layers/shader_object.cpp
tests/shader_object_tests.cpp

Fix setting handles to null in x86

---

CMakeLists.txt
layers/CMakeLists.txt
layers/timeline_semaphore.c
scripts/CMakeLists.txt
tests/CMakeLists.txt
utils/CMakeLists.txt

A PR mainly also to try to understand the issue Jeremy experienced...

cmake: Use common LunarG function for build config

---

scripts/known_good.json

build: Update Vulkan-Headers and VUL to 1.3.268

---

scripts/CMakeLists.txt
scripts/update_deps.py

Fix iOS and other cross-compilation scenarios
QoL updates

scripts: Update UPDATE_DEPS

---

.github/workflows/ci.yml
BUILD.md
CMakeLists.txt
tests/CMakeLists.txt

None of the layers use these libraries.

vel: Remove unused WSI library complexity

---

tests/android/README.md

Realized this when helping @charles-lunarg fix Android crash

android: Minor doc fix

---

scripts/known_good.json

build: Update Vulkan-Headers and VUL to 1.3.281

---

scripts/known_good.json

SPIRV-Headers has not changed this week.

build: Update SPIRV-Tools and glslang to latest

---

scripts/known_good.json

Once again, no SPIRV-Headers changes

build: Update glslang and SPIRV-Tools

---

layers/shader_object/generated/shader_object_constants.h
layers/shader_object/generated/shader_object_create_device_feature_structs.inl
layers/shader_object/generated/shader_object_device_data_declare_extension_variables.inl
layers/shader_object/generated/shader_object_device_data_dynamic_state_adding.inl
layers/shader_object/generated/shader_object_device_data_set_extension_variables.inl
layers/shader_object/generated/shader_object_entry_points_x_macros.inl
layers/shader_object/generated/shader_object_find_intercepted_dynamic_state_function_by_name.inl
layers/shader_object/generated/shader_object_full_draw_state_struct_members.cpp
layers/shader_object/generated/shader_object_full_draw_state_struct_members.inl
layers/shader_object/generated/shader_object_full_draw_state_utility_functions.inl
layers/shader_object/shader_object.cpp
scripts/shader_object_data.json
scripts/shader_object_generator.py

shaderObject: Fix object name crash

---

layers/shader_object/shader_object.cpp

shaderObject: Fix tessellation create info

---

layers/shader_object/shader_object.cpp

Do not compare pointers to arrays, compare characters instead

shader_object: Fix string comparison

---

layers/synchronization2.cpp

sync2: Fix sync2 stage mask

---

scripts/known_good.json

build: Update Vulkan-Headers and VUL to 1.4.309

---

layers/shader_object/shader_object.cpp

shaderObject: Fix creating pipeline with only one tess stage

---

tests/shader_object_tests.cpp

tests: Fix float compare

---

tests/shader_object_tests.cpp
tests/vkrenderframework.cpp

tests: Fix validation errors
