layers/CMakeLists.txt
The mk_layer_config_dir target conflicts with a target in Vuklan-ValidationLayers.
This occurs on Windows and macOS.
=> Avoid CMake target name conflict on Windows, APPLE

layers/CMakeLists.txt, layers/timeline_semaphore.c, layers/vk_alloc.h, layers/vk_util.h
- Specify sufficient POSIX_C_SOURCE date to pull in
pthread_condattr_setclock
- Include time.h, assert.h, string.h as required
- Avoid "restrict" keyword in C++ compilation mode
=> Fix strict Linux portability issues

layers/timeline_semaphore.c
Semaphore should be unmapped while it's destroyed.
Change-Id: I6981ab86250c46a5a4292577906376416ff6ebd4
=> Fix a minor leak issue of semaphore

layers/timeline_semaphore.c
The tiemlineSemaphore of VkPhysicalDeviceVulkan12Features should be set
true
Change-Id: Ib1459457b049e4e789235753790a918719f1af25
=> Fix an issue of timeline_GetPhysicalDeviceFeatures2

layers/timeline_semaphore.c
maxTimelineSemaphoreValueDifference of
VkPhysicalDeviceVulkan12Properties should be set with UINT64_MAX
Change-Id: I06fe5963327f904c9d5fd439cbdac203c750477e
=> Fix an issue of timeline_GetPhysicalDeviceProperties2

layers/timeline_semaphore.c
timelineSemaphore should not be set true for ICD because ICD possibly
doesn't support timelineSemaphore and results in create ICD device
failed.
Since the create info passed from application is const, timeline
semaphore layer has to clone the create info and overwrite the
timelineSemaphore flag with false.
Change-Id: Iafe17dbb21ac7b2b85811178b558849c19126de0
=> Overwrite timelineSemaphore flag of device create info

layers/CMakeLists.txt
See https://github.com/KhronosGroup/Vulkan-ExtensionLayer/blob/6637499182fa76620a8177b47cae871203e481b9/CMakeLists.txt#L44-L55 for where this is defined.
This fixes the build of `VkLayer_khronos_timeline_semaphore` for me with a `Vulkan::Headers` target in my project. Without this change, I see errors about unknown type names (e.g. `VkSemaphoreTypeCreateInfo`), since my (outdated) system `/usr/include/vulkan/vulkan_core.h` is used instead of the in-project `Vulkan-Headers/include/vulkan/vulkan_core.h`.
=> Fix VulkanHeaders_INCLUDE_DIRS typo.

layers/synchronization2.cpp, layers/synchronization2.h
So forgot that Android loader for explicit layers uses the v0 loader-layer interface. The tests should be running with the layer explicitly set but the [Android loader](https://android.googlesource.com/platform/frameworks/native/+/refs/heads/master/vulkan/libvulkan/layers_extensions.cpp#182) needs some functions exposed
There are some random other nit fixes in this as well.
Marked as `WIP` for now as I need to give the loader/layer interface a read-over and go back and see what the proper way to add Android layer support was
=> [WIP] Fix layers to load with Explicit Android Layer

layers/CMakeLists.txt
In commit 358d326c7 I didn't notice that VK_VERSION 1.1 was
hardcoded to 1.1.x in 2 different locations.
=> layers: Fix json VK_VERSION in the install target

layers/synchronization2.cpp, utils/log.h
Still trying to finalize that sync2 works on all Android devices and while debugging I quick added the `utils/log.h` for both ease of using `LOG` but mainly because `assert()` on Android by default will not actually assert and go unoticed
The following message is now being caught on Android
```
F VulkanExtensionLayers: ASSERT: chain_info != NULL at jni/../../layers/synchronization2.cpp:368
```
as to why the `VkCreateDevice` chain be sent from the loader is wrong, still looking into, but wanted to make this a separate PR regardless
=> Add Android Assert support

layers/CMakeLists.txt, layers/synchronization2.cpp, layers/synchronization2.h
Query for timeline semaphores, device groups and protected memory
before including their structures in the translated submit info.
Change-Id: Ifbd040c3bdeac1f1dff68dd30557f90810e44aea
=> synchronization2: Query for features used in vkQueueSubmit2KHR

tests/synchronization2_tests.cpp
Trivial issue/fix
I was curious and swapped the order of the Validation Layers and Sync2 layer for the tests and caught this
=> sync2: Fix small sType typo

layers/json/VkLayer_khronos_synchronization2.json.in
A bug caused old versions of vkconfig to crash when loading the layers settings from the layer repository.
To workaround this issue, the layer schema was modified, this change makes the layer manifest to match the updated layer schema.
This change need to be cherry picked to SDK-1.2.176 branch.
=> synchronization2: fix layer settings to match layer schema

layers/json/VkLayer_khronos_synchronization2.json.in
- The URL was pointing the validation layer sync object instead of the layer documentation.
- Add an the 'introduction' field which is use by Vulkan Configurator to describ the layer to the Vulkan developers and within the layer HTML user documentation generated by Vulkan Configurator.
=> manifest: fix url, add introduction

layers/synchronization2.cpp, layers/synchronization2.h, tests/extension_layer_tests.cpp, tests/synchronization2_tests.cpp
Hook vkGetSwapchainImagesKHR() and related functions so that we can track state for swapchain images.
Fixes #90
=> sync2: Add handling for swapchain images

.github/workflows/build_windows.yml
=> ci: Remove windows-2016 github actions runner

build-android/jni/Android.mk
When building for Android, binaries are produced for `VK_LAYER_KHRONOS_synchronization2`, but not for `VK_LAYER_KHRONOS_timeline_semaphore`.
This PR modifies `build-android/jni/Android.mk` to add LOCAL_MODULE `VkLayer_khronos_timeline_semaphore` so that the binaries for `VK_LAYER_KHRONOS_timeline_semaphore` are built.
The layer has been tested to work on my Galaxy S20 Ultra with Adreno 650, Qualcomm driver version `512.444.0`, which doesn't natively support `VK_KHR_timeline_semaphore`.
Fixes issue #117.
=> Build `VK_LAYER_KHRONOS_timeline_semaphore` for Android

scripts/known_good.json, scripts/update_deps.py
Some of the "prebuild" command lines require execution of Python; but running the "python" command doesn't work on some systems (e.g. Linux systems that use "python" to mean Python 2 and "python3" to refer to Python 3, that don't happen to have Python 2 installed), and can cause the invocation of an unknown Python in any case (e.g. if a script is started with Python3.7, but there's also an installed Python2, the "wrong" Python may be invoked).
This fix allows a syntax, "{python}", that can be used for command strings in known_good.json.  The command strings are formatted to replace "{python}" with a value dependent on the system runtime, and then are split via shlex.split() and invoked.
update_deps.py:
- define a split_command() function that both formats and splits a command line
- use …
=> scripts: use current Python executable when running command lines

layers/synchronization2.cpp, tests/synchronization2_tests.cpp
1. Previously, the Sync2 layer would delete the Sync2FeaturesKHR struct
as if it was a VkBaseInObject, which woudld trigger memory checkers due
to deleting an object of a smaller size than what was initialized.
2. If the application didn't provide enough space for all of the physical
devices enumerated, this would cause the Sync2 layer to just not initialize
its internal list of physical devices, leading to subsequent crashes.
3. Tests were using raw new which would leak the objects.
=> Fix Issues detected with Address Sanitizer

scripts/known_good.json
Updates the known_good.json to use the commits associated with the 1.3.243 SDK release.
=> build: Update glslang/SPIRV-Headers used

.github/workflows/build_android.yml, .github/workflows/build_linux.yml, .github/workflows/build_windows.yml, scripts/generate_source.py
The scripts all need to know the registry directory already, so they can update sys.path to include it.
=> scripts: Remove the need to set PYTHONPATH everywhere

layers/shader_object.cpp, layers/synchronization2.cpp, tests/synchronization2_tests.cpp, tests/vkrenderframework.h, utils/vk_layer_config.cpp, utils/vk_layer_config.h
Make sure we're testing the layer and not the underlying driver by default.
The new SetEnvironment() does not overwrite existing values, so if you REALLY want to test the driver just set `VK_SYNC2_FORCE_ENABLE=0` before running the tests.
=>  tests: Set VK_SYNC2_FORCE_ENABLE when running sync2 tests

build-android/update_external_sources_android.bat, build-android/update_external_sources_android.sh
It is included in recent NDKs and there's no reason to try to build it ourselves.
Fixes #208
=> build-android: No need to build shaderc

layers/shader_object.cpp
viewportCount must be 0 if VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT is used and scissorCount must be 0 if VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT is used
=> shaderObject: Fix viewport and scissor count

layers/CMakeLists.txt
From the F2F notes: "There aren’t current plans to include it in the SDK. It is emulating an Nvidia only extension"
=> Remove VkLayer_khronos_memory_decompression from installation

tests/decompression_tests.cpp, tests/synchronization2_tests.cpp
It looks like calling GTEST_SKIP() inside of SetUp() methods doesn't actually skip the test body, even though the documentation says it does. Move some of the init code to the test bodies to work around this.
=> tests: Fix crashes when the layer under test isn't found

tests/CMakeLists.txt, tests/extension_layer_tests.cpp, tests/generator_source/test_layer_location.h, utils/vk_layer_config.cpp
When tests are executing, they need to find the layers built by this project. However, the only robust way to do that is to set the VK_LAYER_PATH environment variable with the correct path. While it would be simple to set the build path of the layers into a header file, because of multi-configuration (like visual studio), some extra CMake logic is required to rename the header file containing the path using the current build configuration as the source.
=> Make tests use VK_LAYER_PATH by default

layers/generated/shader_object_constants.h, layers/shader_object.cpp, scripts/shader_object_data.json
Some drivers fail a lot of CTS tests with GPL enabled, disable using it until it is resolved
=> shaderObject: Disable GPL on some drivers

layers/shader_object.cpp
This is a workaround for a driver bug which reads from pointers even when count is 0
=> shaderObject: Set description pointers to null when count is 0

layers/json/VkLayer_khronos_shader_object.json.in, layers/json/VkLayer_khronos_timeline_semaphore.json.in
The `spec_version` field is expected to be a string containing a number rather than a raw number. This commit fixes both the timeline sempahore layer and the shader object layer to conform.
=> layers: Use correct JSON type in manifests

layers/generated/shader_object_constants.h, scripts/shader_object_data.json
For any extension being enabled on a device, their dependencies must be in the ppEnabledExtensionNames list as well
=> shaderObject: Add missing extensions

layers/decompression/decompression.cpp
EnumeratePhysicalDevices was only looking for VK_SUCCESS when trying to update its own maps of found physical device handles. This is a problem when the application intentionally only queries for 1 physical device, getting VK_INCOMPLETE but not following up for all physical devices. The tests intentionally look for 1 physical device, triggering this error.
The fix is to update the map of found physical devices if either VK_SUCCESS or VK_INCOMPLETE is returned.
=> layers: Fix EnumPhysDevs in decompression

CMakeLists.txt, build-android/jni/Android.mk, tests/CMakeLists.txt, utils/CMakeLists.txt
- cmake: Fix vulkan platform defines
- cmake: Fix visibility code
- cmake: Remove old workaround for VS 2015
- cmake: Remove ANNOTATED_SPEC_LINK
- cmake: Remove NV_EXTENSIONS AMD_EXTENSIONS
=> CMake Cleanup: Compile Definitions and visibility

tests/synchronization2_tests.cpp
Image view format must match the format of the swapchain image
=> tests: Fix sync2 swapchain image test

layers/shader_object.cpp, tests/shader_object_tests.cpp
Make sure the correct VkResult is returned
The issue was that VkResult could be overwritten if it was anything other than VK_SUCCESS
=> shaderObject: Fix creating shaders with incompatible binary

CMakeLists.txt, layers/CMakeLists.txt, tests/CMakeLists.txt, utils/CMakeLists.txt
Only enable the CXX language to simplify CMake code
Cleanup various compiler options/settings to roughly match VVL.
=> cmake: Cleanup compiler/language usage

layers/shader_object.cpp
=> shaderObject: Fix binding pipeline if created in another thread

layers/generated/shader_object_full_draw_state_struct_members.inl, layers/shader_object.cpp, scripts/shader_object_data.json, scripts/shader_object_generator.py
closes #269 
It is a quite hacky way to do it as I am not familiar with the code generator.
It breaks the interfaces of `GetShader`/`GetShaderPtr`, but fixes its uses by adding `.pShader`.
What was changed is that every `Shader` holds unique `id` in it and `FullDrawStateData` holds it too, so even if different `Shader` gets the same address as one beforehand it is still differentiated from the old one by `id`.
=> shaderObject: Fix potential use of wrong pipeline

layers/generated/shader_object_full_draw_state_utility_functions.inl, layers/shader_object.cpp, scripts/shader_object_generator.py
The fix of alignment issues didn't fix them (memory was allocated with respect to alignment, but there were still issues e.g. in `FullDrawStateData` that storage was calculated in different order than actually assigned and also was not properly aligned).
I've rewritten the change to support any change to alignment and made it actually align the pointers and made the bytes alignment process more explicit.
Also fixed too late allocation of private slots.
=> shaderObject: Fix alignment fix

docs/memory_decompression_layer.md, docs/shader_object_layer.md, docs/synchronization2_layer.md, layers/decompression/decompression.cpp, layers/json/VkLayer_khronos_memory_decompression.json.in, layers/json/VkLayer_khronos_synchronization2.json.in, layers/shader_object.cpp, layers/synchronization2.cpp, tests/synchronization2_tests.cpp
This change enables [using the Layer Settings library](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/254) that implement the VK_EXT_layer_settings extension allowing to control layer programmatically.
=> layers: Fix inconsistant naming convensions

layers/json/VkLayer_khronos_shader_object.json.in
Noticed this during SDK testing. All other extension layers mention Khronos in the description.
=> doc: Fix inconsistent json description

scripts/android.py, tests/android/AndroidManifest.xml, tests/android/res/values/strings.xml
Currently the only reason we need strings.xml is due to the usage of @string/app_name in AndroidManifest.xml
=> android: Remove strings.xml

layers/shader_object.cpp
Currently the layer uses the wrong sType for its VkDevicePrivateDataCreateInfo which leads to a validation error and probably unintended behavior.
=> layers: Use correct sType

layers/decompression/decompression.cpp, layers/shader_object.cpp, layers/synchronization2.cpp, scripts/known_good.json
If the application developer set unknown settings, the layers log these settings.
Change to satisfy VK_EXT_layer_settings spec review.
Also fix broken setting names !
=> layers: Implement vlGetUnknownSettings

layers/decompression/decompression.cpp, layers/shader_object.cpp, layers/synchronization2.cpp, scripts/known_good.json
No codegen changes from this update, but VUL functions got renamed from vl* to vku*.
=> build: Update Vulkan-Headers and VUL to 1.3.265

tests/test_common.h, tests/vktestbinding.cpp, tests/vktestbinding.h, tests/vktestframework.cpp
This will automatically report useful information such as non-success error codes.  These are fatal errors but ASSERT_*() won't work right in object methods.
=> tests: Replace custom EXPECT() macro with gtest EXPECT_*()

tests/extension_layer_tests.cpp
Add a listener to the test framework which throws an exceptions when a test failure occurs. This makes it so that all failed assertions will cause tests to stop executing and begin tearing down, rather than allowing subsequent test code to run, which may put drivers in a bad state.
=> tests: Make failed assertions throw

tests/synchronization2_tests.cpp
Added portability extension for Apple Platforms to Sync2 tests.
=> Tests: add portability for sync2 tests

layers/CMakeLists.txt
Apples App store rules require dynamic libraries be packaged as Frameworks for iOS. This requirement is not applied for macOS, so all iOS libraries should be packaged as Frameworks moving forward to comply with Apples policy. These two layers in particular (synch2 and Shader Objects) are likely to be shipped in an application bundle and thus must be Frameworks for shipping iOS applications.
=> layers: Build ios layers as frameworks instead of dylib

layers/synchronization2.cpp
When the device natively supports the sync2 extension,
the `EnumerateDeviceExtensionProperties` implementation of the sync2 layer would return into `pPropertyCount` `<the count value down chain> + 1`, same as when the device does NOT natively support it.
This is inconsistent with the layer's behavior because in this case it would not add the extension into `pProperties`.
This resulted in e.g. [`ash::instance::Instance::enumerate_device_extension_properties`](https://docs.rs/ash/latest/ash/struct.Instance.html#method.enumerate_device_extension_properties) returning a `Vec<ExtensionProperties>` with an uninitialized `ExtensionProperties` value at the back.
=> Fix sync2 `EnumerateDeviceExtensionProperties` returning incorrect `pPropertyCount` when sync2 is natively supported

layers/CMakeLists.txt
Add Apple appstore required version strings to Info.plist for shader objects and synchronization2 Frameworks.
=> apple: Add version strings to Info.plist

tests/synchronization2_tests.cpp
This test is crashing RADV systems.
See  #372
=> tests: Disable Sync2Test.WaitEventThenSet

tests/extension_layer_tests.cpp
`multiviewMeshShader` and `primitiveFragmentShadingRateMeshShader` must not be enabled, because the features they depend on aren't enabled either.
=> tests: Fix enabling features

layers/shader_object.cpp
The default value for patch control points should be 1. There are cases currently where validation errors are reported due to 0 not being a valid value for patch control points.
=> shaderObject: Fix default patch control points

layers/shader_object.cpp
When graphics pipeline library with `VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_SHADER_BIT_EXT` is being created, `VkPipelineMultisampleStateCreateInfo::pSampleMask` should be initialized to the default value, as that is also what the fully compiled pipeline will use and they must match
=> shaderObject: Fix initializing pSampleMask

tests/android/AndroidManifest.xml
There's an issue with Android 14 that will cause a prompt to display on the phone  when trying to run tests. This can cause an issue with CI as the prompt needs to be hit before the tests begin to run. The prompt displays:
```
This app was built for an older version of Android. It might not work
properly and doesn't include the latest security and privacy
protections.  Check for an update, or contact the app's developer
```
Similar issue on VVL and gfxreconstruct:
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8045
- https://github.com/LunarG/gfxreconstruct/pull/1079
tests/android/AndroidManifest.xml:
- Update targetSdkVersion from 26 to 33
=> tests: Update android targetSdkVersion from 26 to 33

layers/timeline_semaphore.c, utils/log.h
When the device's native driver implements the `VK_EXT_debug_utils` extension,
its `vkSetDebugUtilsObjectNameEXT` would crash for `VkSemaphore`'s generated by the timeline semaphore extension layer.
=> Fix crash in driver-implemented `vkSetDebugUtilsObjectNameEXT` for `VkSemaphore`'s generated by the extention layer

layers/shader_object/shader_object.cpp
See initialization flow: https://github.com/KhronosGroup/Vulkan-ExtensionLayer/blob/main/layers/shader_object/generated/shader_object_create_device_feature_structs.inl
=> shaderObject: Fix null pointer dereference if privateData or dynamicRendering not supported

layers/shader_object/generated/shader_object_create_device_feature_structs.inl, layers/shader_object/shader_object.cpp, scripts/shader_object_data.json, scripts/shader_object_generator.py
If `VkPhysicalDeviceVulkan13Features` is used then `VkPhysicalDeviceDynamicRenderingFeatures` and `VkPhysicalDevicePrivateDataFeaturesEXT` cannot be included
=> shaderObject: Fix appending physical device features

layers/decompression/decompression.cpp, layers/decompression/decompression.h
The existing implementation has hooks for
vkGetPhysicalDeviceFeatures2 and vkGetPhysicalDeviceProperties2 that just call to the underlying implementation. We need to know what the underlying implementation supports to determine if the layer should activate, but if the underlying implementation does not support the decompression extension, the existing hooks won't report the decompression features and properties, even when the layer is active.
This commit moves the feature + property queries for the underlying implementation to vkGetPhysicalDeviceFeatures2Internal and GetPhysicalDeviceProperties2Internal so the hooks for vkGetPhysicalDeviceFeatures2 and vkGetPhysicalDeviceProperties2 can properly report decompression attributes when the extension implementation is provided by the layer. …
=> decompression: Report features and properties

layers/timeline_semaphore.c
The implementation of fill_device_vtable would set the vkGetDeviceProcAddr to the value of the next layer's instead of itself, so calls to timeline semaphore's GetDeviceProcAddr would skip any layer after itself.
=> timeline_semaphore: Use correct GetDeviceProcAddr

layers/shader_object/shader_object.cpp
This seems harmless and should not affect anything, but it fixes a crash on one device in CI
Closes #448
=> shaderObject: Reorder destroying objects

scripts/known_good.json
Modules are defaulted to off, so setting it manually isn't necessary.
=> scripts: Remove useless VulkanHeaders cmake option

layers/timeline_semaphore.c
Add vk_device_create_info_type_size support for anumber of missing structures:
- VkPhysicalDeviceDynamicRenderingFeatures
- VkPhysicalDeviceDynamicRenderingLocalReadFeaturesKHR
- VkPhysicalDeviceSynchronization2Features
- VkPhysicalDeviceVulkan13Features
=> layers: Add missing structures to switch

layers/CMakeLists.txt, layers/decompression/decompression.cpp, layers/synchronization2.cpp, utils/allocator.h
From asking around, seems no one could find a reason why we had exceptions here and only reasons why we should not have them.
I was surprised to find these here and we already return `VkResult` where possible
=> layers: Remove C++ exceptions
